services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: <username>
      POSTGRESQL_PASSWORD: <password>
      POSTGRESQL_DATABASE: postgres
      ALLOW_EMPTY_PASSWORD: flase
    volumes:
      # 主要 data 目录要有 1001 用户和用户组权限
      # chown 1001:1001 -R data
      - ./data:/bitnami/postgresql
