services:
  db:
    image: bitnami/postgresql:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRESQL_USERNAME: <username>
      POSTGRESQL_PASSWORD: <password>
      POSTGRESQL_DATABASE: postgres
      ALLOW_EMPTY_PASSWORD: flase
    volumes:
      - ./data:/bitnami/postgresql
