services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - ./conf:/etc/caddy      # Caddyfiles
      - ./site:/srv            # site's static files
      - ./data:/data           # TLS certificates and other important assets
      - ./config:/config       # configurations
      - ./log:/var/log         # logs
    networks:
      - common-net
networks:
  common-net:
    external: true