version: "3.9"

services:
  mongodb:
    image: docker.io/bitnami/mongodb:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'

volumes:
  mongodb_data:
    driver: local
