services:
  nginx:
    container_name: nginx
    image: nginx:latest
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./ssl_cert:/etc/nginx/ssl_cert
    network_mode: "host"
