services:
  redis-master:
    image: 'bitnami/redis:latest'
    ports:
      - '63790:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=foobared
    volumes:
      - './data/master:/bitnami/data'

  redis-replica:
    image: 'bitnami/redis:latest'
    ports:
      - '63791:6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=foobared
      - REDIS_PASSWORD=foobared
    volumes:
      - './data/slave:/bitnami/data'