services:
  mysql:
    container_name: mysql
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: integration_test
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
    volumes:
      - ./data:/var/lib/mysql
